[build]
  base = "client"  # This is the directory where your client code is located
  publish = "client/build"  # Adjust this path according to your build output
  command = "npm run build"  # Your build command for the client
